"""remove data_atualizacao column from clientes table

Revision ID: 4a628181284f
Revises: bc520a607576
Create Date: 2025-08-23 12:05:14.690826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a628181284f'
down_revision = 'bc520a607576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar se a coluna existe antes de tentar remover
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('clientes')]
    
    if 'data_atualizacao' in columns:
        with op.batch_alter_table('clientes', schema=None) as batch_op:
            batch_op.drop_column('data_atualizacao')
    else:
        print("Column data_atualizacao does not exist, skipping drop")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_atualizacao', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
