"""add tipo_cobranca to ordem_servico

Revision ID: 852d013629c4
Revises: ebff3188124c
Create Date: 2025-07-25 17:49:53.079068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852d013629c4'
down_revision = 'ebff3188124c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_cobranca', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('tipo_cobranca')

    # ### end Alembic commands ###
