"""Adiciona cliente_id em ordens_servico

Revision ID: 97dc07770612
Revises: 
Create Date: 2025-07-23 02:24:31.984436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dc07770612'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_ordens_servico_cliente_id',
            'clientes',
            ['cliente_id'],
            ['id']
        )

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('numero_serie')

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), nullable=True))

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_serie', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ordens_servico_cliente_id', type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
