"""Adiciona campos de equipamento, problema, descrição, outras informações, condições de pagamento e parcelas na OS

Revision ID: b218950f8645
Revises: c9fa47dc9b66
Create Date: 2025-07-25 12:51:25.266738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = 'b218950f8645'
down_revision = 'c9fa47dc9b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcelas', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.drop_column('condicoes_pagamento')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('condicoes_pagamento', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('parcelas')

    # ### end Alembic commands ###
