"""Nomeando UniqueConstraint para fornecedores

Revision ID: bc520a607576
Revises: 
Create Date: 2025-08-21 09:17:40.184633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'bc520a607576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if conn.dialect.has_table(conn, '_alembic_tmp_clientes'):
        op.drop_table('_alembic_tmp_clientes')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=18),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=9),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('complemento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_clientes_cpf_cnpj', ['cpf_cnpj'])
        conn = op.get_bind()
        inspector = inspect(conn)
        columns = [col['name'] for col in inspector.get_columns('clientes')]
        if 'estado' in columns:
            batch_op.drop_column('estado')

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
        columns = [col['name'] for col in inspector.get_columns('fornecedores')]
        if 'nome_fantasia' in columns:
            batch_op.alter_column('nome_fantasia',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=200),
                   existing_nullable=True)
        if 'cpf_cnpj' in columns:
            batch_op.alter_column('cpf_cnpj',
                   existing_type=sa.VARCHAR(length=18),
                   nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=9),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        if 'complemento' in columns:
            batch_op.alter_column('complemento',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=100),
                   existing_nullable=True)
        if 'bairro' in columns:
            batch_op.alter_column('bairro',
                   existing_type=sa.VARCHAR(length=80),
                   type_=sa.String(length=100),
                   existing_nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_fornecedores_codigo', ['codigo'])
        # Fix: Remove line that creates constraint for non-existent column
        # batch_op.create_unique_constraint('uq_fornecedores_cpf_cnpj', ['cpf_cnpj'])
        if 'estado' in columns:
            batch_op.drop_column('estado')
        # Fix: Don't drop cnpj column as it's needed
        # batch_op.drop_column('cnpj')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=2), nullable=True))
        batch_op.drop_constraint('uq_fornecedores_cpf_cnpj', type_='unique')
        batch_op.drop_constraint('uq_fornecedores_codigo', type_='unique')
        batch_op.alter_column('cidade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('bairro',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('complemento',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=2), nullable=True))
        batch_op.drop_constraint('uq_clientes_cpf_cnpj', type_='unique')
        batch_op.alter_column('cidade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('bairro',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('complemento',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.create_table('_alembic_tmp_clientes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.VARCHAR(length=18), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cep', sa.VARCHAR(length=9), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=True),
    sa.Column('numero', sa.VARCHAR(length=10), nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nome_fantasia', sa.VARCHAR(length=200), nullable=True),
    sa.Column('complemento', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uf', sa.VARCHAR(length=2), nullable=True),
    sa.Column('pais', sa.VARCHAR(length=50), server_default=sa.text("'Brasil'"), nullable=True),
    sa.Column('inscricao_estadual', sa.VARCHAR(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.VARCHAR(length=20), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('data_atualizacao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('cpf_cnpj', name=op.f('uq_clientes_cpf_cnpj'))
    )
    # ### end Alembic commands ###
