"""Adiciona campo tecnico em OrdemServico

Revision ID: c9fa47dc9b66
Revises: f3c97be02ac8
Create Date: 2025-07-24 00:13:40.908407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fa47dc9b66'
down_revision = 'f3c97be02ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tecnico', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('tecnico')

    # ### end Alembic commands ###
