"""Atualiza ordem_servico para garantir compatibilidade com o modelo atual

Revision ID: d1091f080006
Revises: c1fef14f0146
Create Date: 2025-09-01 10:08:06.567413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1091f080006'
down_revision = 'c1fef14f0146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'nome',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('clientes', 'cpf_cnpj',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('clientes', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('clientes', 'cep',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('clientes', 'endereco',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('clientes', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('fornecedores', 'nome',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('fornecedores', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('fornecedores', 'cep',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('fornecedores', 'endereco',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_produtos_fornecedor_id_fornecedores'), 'produtos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_produtos_fornecedor_id_fornecedores'), 'produtos', 'fornecedores', ['fornecedor_id'], ['id'], ondelete='SET NULL')
    op.alter_column('fornecedores', 'endereco',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('fornecedores', 'cep',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.alter_column('fornecedores', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('fornecedores', 'nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('clientes', 'nome_fantasia',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('clientes', 'endereco',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('clientes', 'cep',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.alter_column('clientes', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clientes', 'cpf_cnpj',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=18),
               existing_nullable=True)
    op.alter_column('clientes', 'nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
