"""Adiciona campo servicos na OrdemServico

Revision ID: da66f1c6d23b
Revises: 97dc07770612
Create Date: 2025-07-23 03:21:23.203541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da66f1c6d23b'
down_revision = '97dc07770612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicos', sa.Text(), nullable=True))
        batch_op.drop_column('produtos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtos', sa.TEXT(), nullable=True))
        batch_op.drop_column('servicos')

    # ### end Alembic commands ###
