"""Add equipment, description, payment parcels

Revision ID: ebff3188124c
Revises: b218950f8645
Create Date: 2025-07-25 13:15:04.237235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebff3188124c'
down_revision = 'b218950f8645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipamento_nome', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('equipamento_marca', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('equipamento_modelo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('equipamento_numero_serie', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('equipamento_acessorios', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('equipamento_problema', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('descricao_servico_realizado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('condicoes_pagamento', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pago_parcelado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('outras_informacoes', sa.Text(), nullable=True))
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('tecnico_responsavel',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('tecnico')
        batch_op.drop_column('descricao_servico')
        batch_op.drop_column('servico_nome')
        batch_op.drop_column('qtd_servico')
        batch_op.drop_column('valor_unit_servico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_unit_servico', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('qtd_servico', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('servico_nome', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('descricao_servico', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tecnico', sa.VARCHAR(length=120), nullable=True))
        batch_op.alter_column('tecnico_responsavel',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('outras_informacoes')
        batch_op.drop_column('pago_parcelado')
        batch_op.drop_column('condicoes_pagamento')
        batch_op.drop_column('descricao_servico_realizado')
        batch_op.drop_column('equipamento_problema')
        batch_op.drop_column('equipamento_acessorios')
        batch_op.drop_column('equipamento_numero_serie')
        batch_op.drop_column('equipamento_modelo')
        batch_op.drop_column('equipamento_marca')
        batch_op.drop_column('equipamento_nome')

    # ### end Alembic commands ###
