"""Adiciona campo produtos na OrdemServico

Revision ID: f3c97be02ac8
Revises: da66f1c6d23b
Create Date: 2025-07-23 03:23:41.089446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c97be02ac8'
down_revision = 'da66f1c6d23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('produtos')

    # ### end Alembic commands ###
